name: FFN

INPUT_OUTPUT:
  coord_mode: 2                # 0: [0, H-1] x [0, W-1], 1: [0, 1]^2,  2: [-1, 1]^2
  data_range: 1                # 1: [0, 1]^2,  2: [-1, 1]^2

NET:
  lr: 0.001
  num_layers: 4
  dim_hidden: 256
  num_frequencies: 128
  use_bias: True


INPUT_OUTPUT_IMG:
  coord_mode: 2                # 0: [0, H-1] x [0, W-1], 1: [0, 1]^2,  2: [-1, 1]^2
  data_range: 1                # 1: [0, 1]^2,  2: [-1, 1]^2

NET_IMG:
  lr: 0.001
  num_layers: 4
  dim_hidden: 256
  num_frequencies: 128
  use_bias: True