name: SIREN

# Generic configs
INPUT_OUTPUT:
  coord_mode: 1                # 0: [0, H-1] x [0, W-1], 1: [0, 1]^2,  2: [-1, 1]^2
  data_range: 1                # 1: [0, 1]^2,  2: [-1, 1]^2
  grid_dims: [16, 16]    # [15, 27, 48]

NET:
  lr: 0.0001
  num_layers: 6
  dim_hidden: 512
  w0: 30.0
  w0_initial: 30.0
  use_bias: True

# LibriSpeech Audio configs
INPUT_OUTPUT_AUDIO:
  coord_mode: 2               # 0: [0, H-1] x [0, W-1], 1: [0, 1]^2,  2: [-5, 5]^2
  data_range: 2               # 1: [0, 1]^2,  2: [-1, 1]^2
NET_AUDIO:
  lr: 0.0001
  num_layers: 4
  dim_hidden: 128
  w0: 30.0
  w0_initial: 30.0
  use_bias: True

# Kodak Image configs
INPUT_OUTPUT_IMG:
  coord_mode: 0                # 0: [0, H-1] x [0, W-1], 1: [0, 1]^2,  2: [-1, 1]^2
  data_range: 1                # 1: [0, 1]^2,  2: [-1, 1]^2
  grid_dims: [16, 16] 
NET_IMG:
  lr: 0.0001
  num_layers: 4
  dim_hidden: 256
  w0: 30.0
  w0_initial: 30.0
  use_bias: True


# Megapixel configs
INPUT_OUTPUT_MEGA:
  coord_mode: 0                # 0: [0, H-1] x [0, W-1], 1: [0, 1]^2,  2: [-1, 1]^2
  data_range: 1                # 1: [0, 1]^2,  2: [-1, 1]^2
  grid_dims: [16, 16] 

NET_MEGA:
  lr: 0.0001
  num_layers: 6
  dim_hidden: 512
  w0: 30.0
  w0_initial: 30.0
  use_bias: True


# Video configs
INPUT_OUTPUT_VIDEO:
  coord_mode: 0                # 0: [0, H-1] x [0, W-1], 1: [0, 1]^2,  2: [-1, 1]^2
  data_range: 1                # 1: [0, 1]^2,  2: [-1, 1]^2
  grid_dims: [15, 27, 48]

NET_VIDEO:
  lr: 0.0001
  num_layers: 10
  dim_hidden: 512
  w0: 30.0
  w0_initial: 30.0
  use_bias: True